In [2]:
import numpy as np

In [8]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [15]:
import time
import sys

In [19]:
b=range(1000)
print(sys.getsizeof(5) * len(b))

28000


In [22]:
c = np.arange(1000)
print(c.size*c.itemsize)

4000


In [23]:
size = 100000

In [26]:
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

In [31]:
start = time.time()
result = [(x+y) for x,y in zip(L1, L2)]
#print(result)
print('Python List Tool:',(time.time() - start)*1000)

Python List Tool: 15.95759391784668


In [32]:
start = time.time()
result = A1 + A2
print('Numpy array List Tool:',(time.time() - start)*1000)

Numpy array List Tool: 2.000570297241211


In [33]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
a.ndim

2

In [39]:
a.itemsize

4

In [40]:
a.shape

(3, 2)

In [41]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [42]:
a.itemsize

8

In [43]:
a.shape

(3, 2)

In [44]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.complex)
a

C:\Users\sreenath\AppData\Local\Temp\ipykernel_21404\1207795164.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.array([[1,2],[3,4],[5,6]], dtype = np.complex)


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
l=range(5)
l

range(0, 5)

In [49]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [52]:
print('concatenation example')
print(np.char.add(['hello','hi'], ['abc','xyz']))

concatenation example
['helloabc' 'hixyz']


In [56]:
print(np.char.multiply('hello ', 4))

hello hello hello hello 


In [57]:
print(np.char.center('hello ', 20, fillchar ='-'))

-------hello -------


In [58]:
list1 = [2,4,5,'r',7,8,12]

list2 = [3,6,9,'t',2,1,6]

print(list1[2:-1]+ list2[2:-1])

[5, 'r', 7, 8, 9, 't', 2, 1]
